spring.application.name=kofi

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:kofi}?createDatabaseIfNotExist=true&useSSL=${DB_SSL:false}&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


app.route.password=${APP_ROUTE_PASS:123}

spring.thymeleaf.cache=false

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true