# Conexão MYSQL
spring.application.name=kofi
# Configs
spring.datasource.url=jdbc:mysql://localhost:3306/kofi?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA (Hibernate e JDBC)
spring.jpa.hibernate.ddl-auto=update
# SQL no Terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Desabilitar Cache dos templates
spring.thymeleaf.cache=false
# Live Reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true